language: c
sudo: required
dist: trusty
install:
- sudo apt-get update
# install build tools
- sudo apt-get install automake autoconf libtool
# install libxml2/libxslt libraries
- sudo apt-get install libxml2 libxml2-dev libxslt1.1 libxslt1-dev
# install openssl libraries
- sudo apt-get install libssl1.0.0 libssl-dev
# install nspr/nss libraries
- sudo apt-get install libnspr4 libnspr4-dev libnss3 libnss3-dev libnss3-tools
# install gcrypt libraries
- sudo apt-get install libgcrypt11 libgcrypt11-dev
# install gnutls libraries
- sudo apt-get install libgnutls28 libgnutls-dev
# install sanitizer toolchain
- sudo apt-get install clang-7
script:
- mkdir build && cd build && ../autogen.sh --enable-werror && make && make check
matrix:
  include:
  - name: linux gcc release
  - name: linux clang-7 sanitizers
    env:
    - ASAN_OPTIONS=handle_ioctl=1:detect_leaks=1:allow_user_segv_handler=1:use_sigaltstack=0:detect_deadlocks=1:intercept_tls_get_addr=1:check_initialization_order=1:detect_stack_use_after_return=1:strict_init_order=1:detect_invalid_pointer_pairs=1
    - LSAN_OPTIONS=print_suppressions=0:report_objects=1
    - UBSAN_OPTIONS=print_stacktrace=1
    - CC="clang-7 -fno-sanitize-recover=undefined,integer -fsanitize=address -fsanitize=undefined -fsanitize=local-bounds"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-7
